--liquibase formatted sql

--changeset 12:1asdasd33

use database DEV_TZ;
use schema ACCOUNTING_ANALYTICS;
use role FULL_ACCESS_ROLE;
use warehouse SNOWFLAKE_LEARNING_WH;

CREATE  TABLE IF NOT EXISTS DEV_TZ.ACCOUNTING_ANALYTICS.Student_1(
    ID             NUMBER       PRIMARY KEY,
    NAME           STRING       NOT NULL,
    STATUS         STRING,
    CREATED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);


CREATE  TABLE IF NOT EXISTS DEV_TZ.ACCOUNTING_ANALYTICS.Student_2(
    ID             NUMBER       PRIMARY KEY,
    NAME           STRING       NOT NULL,
    STATUS         STRING,
    CREATED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);


CREATE  TABLE IF NOT EXISTS DEV_TZ.ACCOUNTING_ANALYTICS.Student_3(
    ID             NUMBER       PRIMARY KEY,
    NAME           STRING       NOT NULL,
    STATUS         STRING,
    CREATED_AT     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
