name: Run Python Script

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-connector-python

      - name: Run Python script
        env:
          SNOWFLAKE_USERNAME: ${{ secrets.DEV_SNOWFLAKE_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.DEV_SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: LKGVJUZ-WS14116
          SNOWFLAKE_WAREHOUSE: SNOWFLAKE_LEARNING_WH
          SNOWFLAKE_PRIVATE_KEY_PASSWORD: ${{ secrets.DEV_SNF_USER_PRIVATE_KEY_PASSWORD }}
        run: |
          echo "${{ secrets.DEV_SNF_USER_PRIVATE_KEY }}"
          ls
          pwd
          
          python a.py "DEV" "${{ secrets.DEV_SNOWFLAKE_USERNAME }}" "LKGVJUZ-WS14116" snowflake_rsa_key.p8 "SNOWFLAKE_LEARNING_WH"

