name: Dev - Liquibase deployments 
on: 
  release: 
    types: [ published, edited]
  workflow_dispatch:
    inputs:
      environment:
          required: true
          type: choice
          description: "environment"
          options:
            - "Dev"
      liquibase_tag:
          required: true
          type: string
          description: "Liquibase tag to apply (e.g. liquibase-dev-deploy-123)"
  pull_request:
    types: [ opened, edited ]
    branches:
      - main
  push:
    branches:
      - testing


jobs:   
  DEV_Liquibase_Job:
    if: github.event_name == 'release'
    runs-on: windows-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      
      - name: Fetch all tags
        run: git fetch origin 'refs/tags/*:refs/tags/*' --force
      - name: Install Python dependencies
        run: pip install snowflake-connector-python